### ISSUE TITLE
Remove duplicate muni metro vehicles

### ISSUE THREAD

**Issue by EddyIonescu** [trynmaps/tryn-api#41]
2-car Muni trains (on all lines except J) have both their cars show up in Nextbus. This can be observed on the web-app map.

For the MVP, this causes the median/average observed headways between cars to be much lower than what they really were.

Issues:
1. routes can have a mix of one and two car trains (and in a few years, three).
2. Muni Metro trains can bunch fairly closely, often staying that way for the entire trip. 
3. each car sends its location separately, meaning that coupled cars could sometimes appear as being a block apart.

Notes:
1. Muni trains don't get decoupled when in-service, meaning that if two cars are coupled, then they stay coupled for the entire time they're in-service (unlike the previous Boeing ones did back in the day, where K/L/M trains and N/J trains were often coupled together at West Portal and Duboce as to run more efficiently in the subway; they lost that ability with the current Breda LRVs, and don't have plans for doing this with the new Siemens ones).
2. None of the other agencies available via the API have this issue, so it'll be Muni-specific.

Possible Approaches:
1. Resolve this in the MVP right before returning the state.
2. Correct and clean the vehicles in the S3 store. It would require a better way of storing them (like hourly chunks per agency+route or 15-minute chunks per agency), which would require tryn-api and opentransit-map changes.
3. Clean the vehicles as they are returned by the API. Not recommended since the MVP requests vehicles in 12-minute chunks, which is an issue since two trains could be closely behind one another for the entirety of a 12-minute span.

**Comment by EddyIonescu** [comment]
Update: in-progress with option 1

**Comment by youngj** [comment]
Thanks for working on this! I agree it seems easiest to correct in metrics-mvp. I'm not sure what method you have in mind to remove duplicates before returning the state. It may also be possible to remove duplicates in eclipses.py after buses are loaded into data frame, or after computing arrivals.

**Comment by youngj** [comment]
I just noticed that http://webservices.nextbus.com/service/publicJSONFeed?command=vehicleLocations&a=sf-muni&t=0 has a leadingVehicleId property for each vehicle (also on restbus.info). If we start storing that in orion-vehicles it seems that it would be easy to filter out non-leading vehicles.

**Comment by EddyIonescu** [comment]
@youngj great observation, never really looked into what that was, but obviously it can't be that easy with nextbus.

This is the N Judah at 1:52 PM (Pacific) today: https://jsonblob.com/e29d8255-6089-11e9-95ef-a9f15741649d
The last vehicle has a leading ID of 1452, except that 1452 is nowhere to be found. The vehicle at the 5th index does have a leading vehicle ID, which is at the 6th index.

1. Not all vehicles with a leading ID actually have a leading vehicle if it's not there
2. Vehicles sometimes disappear in a state, but generally come back in the next one

So we'd want to filter out vehicles with a leading ID that exists on that route. Given 2, I wouldn't do this in Orion. Rather, I'd do it in tryn-api over all vehicles being returned, adding a field `numCars` to each vehicle (the 12 and 1 minute time-spans the MVP and map use should be okay).

My initial approach was to find which cars with a smaller ID each car could be linked to in each state, then determine which couplings were mostly consistent across the states; and yes, putting it in eclipses does seem better since it's after being resampled. I haven't made much progress on it yet so I'll skip to the `leadingVehicleId` approach.

**Comment by youngj** [comment]
Good to know about the issues with leadingVehicleId. The approach you described sounds good to me!

The MVP uses a variable chunk size, not necessarily 12 minutes -- could be more or less, but definitely at least 1 minute.
